### ISSUE TITLE
Not working, can't setting up

### ISSUE THREAD

**Issue by Naaach** [openode-io/node-with-local-mysql#1]
Hi i'm trying build and API with this example but after a few tries i can't start the server with the database and express 

````
tasks_api>openode deploy
** New major opeNode version coming next week! Significant revamp of the UI, backend, and new open source free plan. **
[Sun Mar 15 2020 14:08:51 GMT+0100 (Hora estándar romance)] -  [+] Authentication valid.
- Sending files (trial 1) - file=./.gitignore size=13 operation=C
Sending files (trial 1) - file=./app/classes/DEV.js size=377 operation=C
Sending files (trial 1) - file=./app/classes/tasks.js size=826 operation=C
Sending files (trial 1) - file=./app/classes/user.js size=1450 operation=C
Sending files (trial 1) - file=./app/db/db.js size=596 operation=C
Sending files (trial 1) - file=./app/routes/routes.js size=389 operation=C
Sending files (trial 1) - file=./docker-compose.yml size=406 operation=M
Sending files (trial 1) - file=./Dockerfile size=330 operation=C
Sending files (trial 1) - file=./main.js size=549 operation=C
Sending files (trial 1) - file=./package-lock.json size=96851 operation=C
Sending files (trial 1) - file=./package.json size=475 operation=M
Sending files (trial 1) - file=./readame.md size=25 operation=C
| 12/12
[ { location: 'france',
    result: { status: 'Operation in progress' } } ]
Checking credits available
Preparing repository
Clearing website container
Preparing core instance...
Preparing website image and spawning website container (docker-compose)...
Step 1/8 : FROM node:12-alpine
12-alpine: Pulling from library/node
Digest: sha256:bba77d0ca8820b43af898b3c50d4e8b68dc703ebbd958319af2f21f2d3c309f5
Status: Downloaded newer image for node:12-alpine
 ---> 927d03058714
Step 2/8 : WORKDIR /opt/app
 ---> Running in b4721f81f55e
Removing intermediate container b4721f81f55e
 ---> ae56f2e5d529
Step 3/8 : ENV PORT=80
 ---> Running in c88afe193486
Removing intermediate container c88afe193486
 ---> d4290ecf2671
Step 4/8 : ENV MODE=production
 ---> Running in a915928c425d
Removing intermediate container a915928c425d
 ---> 3a24f3fe7bb9
Step 5/8 : RUN echo 'set -e' >> /boot.sh
 ---> Running in 921c5b741411
Removing intermediate container 921c5b741411
 ---> ab0516d95967
Step 6/8 : RUN echo 'crond' >> /boot.sh
 ---> Running in 073b818f9e72
Removing intermediate container 073b818f9e72
 ---> 0bd33985baf0
Step 7/8 : RUN echo 'npm install --production' >> /boot.sh
 ---> Running in aa5086853161
Removing intermediate container aa5086853161
 ---> dc0df641f6d6
Step 8/8 : CMD sh /boot.sh && npm start
 ---> Running in 14d523b98a4d
Removing intermediate container 14d523b98a4d
 ---> 6de13e9c5496
Successfully built 6de13e9c5496
Successfully tagged app_www:latest
latest: Pulling from library/mariadb
Digest: sha256:d1ceee944c90ee3b596266de1b0ac25d2f34adbe9c35156b75bcb9a7047c7545
Status: Downloaded newer image for mariadb:latest
Attaching to tasks-connector, app_mariadb_1
tasks-connector | npm WARN tasks_api@0.1.0 No repository field.
tasks-connector |
tasks-connector | added 2 packages from 2 contributors, removed 4 packages, updated 7 packages and audited 2443 packages in 2.571s
mariadb_1  | 2020-03-15 13:10:26+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.12+maria~bionic started.
tasks-connector | found 97 low severity vulnerabilities
mariadb_1  | 2020-03-15 13:10:26+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
tasks-connector |   run `npm audit fix` to fix them, or `npm audit` for details
mariadb_1  | 2020-03-15 13:10:26+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.12+maria~bionic started.
tasks-connector |
mariadb_1  | 2020-03-15 13:10:27+00:00 [Note] [Entrypoint]: Initializing database files
tasks-connector | > tasks_api@0.1.0 start /opt/app
mariadb_1  |
tasks-connector | > node main.js
tasks-connector |
tasks-connector | All ready on port: 80
tasks-connector | /opt/app/app/db/db.js:14
tasks-connector |   if (err) throw err;
mariadb_1  |
tasks-connector |            ^
mariadb_1  | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
tasks-connector |
tasks-connector | Error: connect ECONNREFUSED 172.19.0.3:3306
mariadb_1  | To do so, start the server, then issue the following commands:
tasks-connector |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
mariadb_1  |
tasks-connector |     --------------------
mariadb_1  | '/usr/bin/mysqladmin' -u root password 'new-password'
tasks-connector |     at Protocol._enqueue (/opt/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mariadb_1  | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
tasks-connector |     at Protocol.handshake (/opt/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
mariadb_1  |
mariadb_1  | Alternatively you can run:
mariadb_1  | '/usr/bin/mysql_secure_installation'
tasks-connector |     at Connection.connect (/opt/app/node_modules/mysql/lib/Connection.js:119:18)
mariadb_1  |
tasks-connector |     at Object.<anonymous> (/opt/app/app/db/db.js:13:12)
mariadb_1  | which will also give you the option of removing the test
tasks-connector |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
mariadb_1  | databases and anonymous user created by default.  This is
tasks-connector |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
mariadb_1  | strongly recommended for production servers.
tasks-connector |     at Module.load (internal/modules/cjs/loader.js:1002:32)
tasks-connector |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
tasks-connector |     at Module.require (internal/modules/cjs/loader.js:1044:19)
tasks-connector |     at require (internal/modules/cjs/helpers.js:77:18) {
mariadb_1  |
tasks-connector |   errno: 'ECONNREFUSED',
mariadb_1  | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
tasks-connector |   code: 'ECONNREFUSED',
mariadb_1  | MySQL manual for more instructions.
tasks-connector |   syscall: 'connect',
mariadb_1  |
tasks-connector |   address: '172.19.0.3',
mariadb_1  | Please report any problems at http://mariadb.org/jira
mariadb_1  |
mariadb_1  | The latest information about MariaDB is available at http://mariadb.org/.
tasks-connector |   port: 3306,
mariadb_1  | You can find additional information about the MySQL part at:
tasks-connector |   fatal: true
mariadb_1  | http://dev.mysql.com
tasks-connector | }
mariadb_1  | Consider joining MariaDB's strong and vibrant community:
tasks-connector | npm ERR! code ELIFECYCLE
mariadb_1  | https://mariadb.org/get-involved/
tasks-connector | npm ERR! errno 1
mariadb_1  |
tasks-connector | npm ERR! tasks_api@0.1.0 start: `node main.js`
mariadb_1  | 2020-03-15 13:10:37+00:00 [Note] [Entrypoint]: Database files initialized
tasks-connector | npm ERR! Exit status 1
mariadb_1  | 2020-03-15 13:10:37+00:00 [Note] [Entrypoint]: Starting temporary server
tasks-connector | npm ERR!
mariadb_1  | 2020-03-15 13:10:37+00:00 [Note] [Entrypoint]: Waiting for server startup
tasks-connector | npm ERR! Failed at the tasks_api@0.1.0 start script.
mariadb_1  | 2020-03-15 13:10:37 0 [Note] mysqld (mysqld 10.4.12-MariaDB-1:10.4.12+maria~bionic) starting as process 124 ...
tasks-connector | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
tasks-connector |
tasks-connector | npm ERR! A complete log of this run can be found in:
tasks-connector | npm ERR!     /root/.npm/_logs/2020-03-15T13_10_48_558Z-debug.log
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1  | 2020-03-15 13:10:37 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: 10.4.12 started; log sequence number 60981; transaction id 21
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mariadb_1  | 2020-03-15 13:10:37 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2020-03-15 13:10:37 0 [Warning] 'user' entry 'root@e62fa75c48d4' ignored in --skip-name-resolve mode.
mariadb_1  | 2020-03-15 13:10:37 0 [Warning] 'user' entry '@e62fa75c48d4' ignored in --skip-name-resolve mode.
mariadb_1  | 2020-03-15 13:10:37 0 [Warning] 'proxies_priv' entry '@% root@e62fa75c48d4' ignored in --skip-name-resolve mode.
mariadb_1  | 2020-03-15 13:10:37 0 [Note] InnoDB: Buffer pool(s) load completed at 200315 13:10:37
mariadb_1  | 2020-03-15 13:10:37 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2020-03-15 13:10:37 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2020-03-15 13:10:37 0 [Note] mysqld: ready for connections.
mariadb_1  | Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
mariadb_1  | 2020-03-15 13:10:38+00:00 [Note] [Entrypoint]: Temporary server started.
[ { 'HTTP(S) port listening': false,
    valid: false,
    'Help Links': { 'View All Docs': 'https://www.openode.io/docs' },
    Error: 'Unable to complete the build successfully.',
    buildDuration: 115.478 } ]
```

**Comment by martinlevesque** [comment]
Hi,

Not sure exactly what is the issue here, however note that it will be deprecated in a matter of days as we will release a new major version of opeNode very soon.

It's recommended to use an external service for a database, or sqlite for a small database.
